In [11]:
print("Hello World")

Hello World

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
data=pd.read_csv('Global_Pollution_Analysis.csv')

In [14]:
data

,Country,Year,Air_Pollution_Index,Water_Pollution_Index,Soil_Pollution_Index,Industrial_Waste (in tons),Energy_Recovered (in GWh),CO2_Emissions (in MT),Renewable_Energy (%),Plastic_Waste_Produced (in tons),Energy_Consumption_Per_Capita (in MWh),Population (in millions),GDP_Per_Capita (in USD)
0,Canada,2006,58.772591,60.060473,28.262554,2.075982e+06,4.665246e+05,1840.011086,9.996433,4.504795e+05,6.796971,652.100562,23396.414919
1,Japan,2019,32.313551,88.623211,11.071318,3.686815e+06,8.163774e+05,3279.231917,22.176904,6.692322e+05,15.179322,1386.574426,16800.549478
2,Canada,2014,54.154987,25.274238,75.340542,2.667501e+06,7.327779e+05,2449.952299,45.713698,6.888802e+05,6.513152,10.330158,17030.007900
3,Brazil,2010,74.404594,41.398791,45.072792,2.200944e+06,4.317517e+05,2962.577475,37.364611,8.549044e+05,13.395765,267.807344,30050.665906
4,USA,2007,77.649382,33.363772,47.756421,3.672880e+06,1.000705e+06,3710.430129,29.961184,9.108989e+05,10.896929,543.709807,22901.752348
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Brazil,2012,91.844582,52.527167,70.419697,4.451993e+06,7.273695e+05,2249.848909,78.165599,1.045183e+06,15.281404,765.852682,39027.022595
96,USA,2008,82.340314,65.484158,71.625198,3.906496e+06,8.996674e+05,2929.682727,39.424174,1.468385e+06,11.363026,1211.645104,44776.579530
97,USA,2014,96.715029,23.364125,26.567964,7.110341e+05,1.315288e+05,1841.276014,46.797903,3.024996e+05,9.682707,1030.134787,6339.641936
98,China,2012,53.152521,86.440201,73.538559,1.709026e+06,3.442646e+05,2018.262340,69.547401,3.660352e+05,17.779977,734.551834,64759.837090
99,China,2000,68.693548,82.067627,51.432212,5.998313e+05,1.326200e+05,2706.101650,45.130229,6.009992e+05,9.515110,1216.743518,27062.598001

In [15]:
data = data.drop(columns=['Country', 'Year'])

In [16]:
data

,Air_Pollution_Index,Water_Pollution_Index,Soil_Pollution_Index,Industrial_Waste (in tons),Energy_Recovered (in GWh),CO2_Emissions (in MT),Renewable_Energy (%),Plastic_Waste_Produced (in tons),Energy_Consumption_Per_Capita (in MWh),Population (in millions),GDP_Per_Capita (in USD)
0,58.772591,60.060473,28.262554,2.075982e+06,4.665246e+05,1840.011086,9.996433,4.504795e+05,6.796971,652.100562,23396.414919
1,32.313551,88.623211,11.071318,3.686815e+06,8.163774e+05,3279.231917,22.176904,6.692322e+05,15.179322,1386.574426,16800.549478
2,54.154987,25.274238,75.340542,2.667501e+06,7.327779e+05,2449.952299,45.713698,6.888802e+05,6.513152,10.330158,17030.007900
3,74.404594,41.398791,45.072792,2.200944e+06,4.317517e+05,2962.577475,37.364611,8.549044e+05,13.395765,267.807344,30050.665906
4,77.649382,33.363772,47.756421,3.672880e+06,1.000705e+06,3710.430129,29.961184,9.108989e+05,10.896929,543.709807,22901.752348
...,...,...,...,...,...,...,...,...,...,...,...
95,91.844582,52.527167,70.419697,4.451993e+06,7.273695e+05,2249.848909,78.165599,1.045183e+06,15.281404,765.852682,39027.022595
96,82.340314,65.484158,71.625198,3.906496e+06,8.996674e+05,2929.682727,39.424174,1.468385e+06,11.363026,1211.645104,44776.579530
97,96.715029,23.364125,26.567964,7.110341e+05,1.315288e+05,1841.276014,46.797903,3.024996e+05,9.682707,1030.134787,6339.641936
98,53.152521,86.440201,73.538559,1.709026e+06,3.442646e+05,2018.262340,69.547401,3.660352e+05,17.779977,734.551834,64759.837090
99,68.693548,82.067627,51.432212,5.998313e+05,1.326200e+05,2706.101650,45.130229,6.009992e+05,9.515110,1216.743518,27062.598001

In [17]:
data.corr()['Energy_Recovered (in GWh)']

Air_Pollution_Index                      -0.080454
Water_Pollution_Index                    -0.104103
Soil_Pollution_Index                      0.127381
Industrial_Waste (in tons)                0.922608
Energy_Recovered (in GWh)                 1.000000
CO2_Emissions (in MT)                     0.056150
Renewable_Energy (%)                     -0.010572
Plastic_Waste_Produced (in tons)          0.032971
Energy_Consumption_Per_Capita (in MWh)   -0.021948
Population (in millions)                 -0.045939
GDP_Per_Capita (in USD)                   0.046102
Name: Energy_Recovered (in GWh), dtype: float64

In [18]:
data_input=data['Industrial_Waste (in tons)']
data_inputy=data['Energy_Recovered (in GWh)']

In [23]:
x=np.array(data_input)
y=np.array(data_inputy)

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [28]:

import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split



model = keras.Sequential([
    keras.layers.Dense(8, activation='relu', input_shape=(1,)),  # FIXED: layers.Dense
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(1)  # Output Layer
])
model.compile(optimizer='adam',loss='mse')
model.fit(x,y,epochs=100,verbose=0)

c:\Users\Asus\100DaysML\MODELS\GlobalDataNN\.venv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
new_waste = np.array([[600]])  # Example: 600 tons of waste
predicted_energy = model.predict(new_waste)
print("Predicted Energy Recovered:", predicted_energy[0][0], "GWh")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Predicted Energy Recovered: 131.50984 GWh