In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot as plt
from sklearn.metrics import mean_squared_error

In [36]:
df=pd.read_csv("Food_Delivery_Time_Prediction.csv")

In [37]:
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,Rainy,Medium,4,Medium,Afternoon,Car,4.1,3.0,26.22,1321.10,81.54
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,Cloudy,Medium,8,Low,Night,Car,4.5,4.2,62.61,152.21,29.02
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,Snowy,Medium,9,High,Night,Bike,3.3,3.4,48.43,1644.38,64.17
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,Cloudy,Low,2,Medium,Evening,Bike,3.2,3.7,111.63,541.25,79.23
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,Rainy,High,6,Low,Night,Bike,3.5,2.8,32.38,619.81,2.34

In [38]:
df.shape

(200, 15)

In [40]:

for col in df.columns:
     if df[col].dtype=='object':
         df[col] = df[col].astype('category').cat.codes

In [41]:
df

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,0,98,10,1.57,1,2,4,2,0,2,4.1,3.0,26.22,1321.10,81.54
1,1,73,50,21.32,0,2,8,1,3,2,4.5,4.2,62.61,152.21,29.02
2,2,79,163,6.95,2,2,9,0,3,1,3.3,3.4,48.43,1644.38,64.17
3,3,160,107,13.79,0,1,2,2,1,1,3.2,3.7,111.63,541.25,79.23
4,4,65,71,6.72,1,0,6,1,3,1,3.5,2.8,32.38,619.81,2.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,117,133,23.82,0,0,8,2,3,1,4.7,4.0,50.39,1432.26,66.34
196,196,189,106,6.09,2,2,8,1,3,0,3.0,3.6,90.54,1720.25,40.27
197,197,58,32,20.61,2,0,4,2,0,1,2.9,3.4,73.20,1356.58,5.10
198,198,1,153,24.06,1,0,9,1,3,2,3.9,4.8,53.94,354.39,85.25
199,199,141,181,9.18,2,1,2,1,2,1,4.6,3.2,78.58,323.73,48.91

In [42]:
df

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,0,98,10,1.57,1,2,4,2,0,2,4.1,3.0,26.22,1321.10,81.54
1,1,73,50,21.32,0,2,8,1,3,2,4.5,4.2,62.61,152.21,29.02
2,2,79,163,6.95,2,2,9,0,3,1,3.3,3.4,48.43,1644.38,64.17
3,3,160,107,13.79,0,1,2,2,1,1,3.2,3.7,111.63,541.25,79.23
4,4,65,71,6.72,1,0,6,1,3,1,3.5,2.8,32.38,619.81,2.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,117,133,23.82,0,0,8,2,3,1,4.7,4.0,50.39,1432.26,66.34
196,196,189,106,6.09,2,2,8,1,3,0,3.0,3.6,90.54,1720.25,40.27
197,197,58,32,20.61,2,0,4,2,0,1,2.9,3.4,73.20,1356.58,5.10
198,198,1,153,24.06,1,0,9,1,3,2,3.9,4.8,53.94,354.39,85.25
199,199,141,181,9.18,2,1,2,1,2,1,4.6,3.2,78.58,323.73,48.91

In [44]:
df[df.columns[1:]].corr()['Delivery_Time'][:]

Customer_Location            -0.034449
Restaurant_Location           0.022135
Distance                     -0.075143
Weather_Conditions           -0.021580
Traffic_Conditions            0.040023
Delivery_Person_Experience   -0.019098
Order_Priority               -0.013405
Order_Time                   -0.008725
Vehicle_Type                 -0.055576
Restaurant_Rating            -0.091855
Customer_Rating              -0.021952
Delivery_Time                 1.000000
Order_Cost                   -0.009307
Tip_Amount                   -0.029154
Name: Delivery_Time, dtype: float64

In [45]:
df['imp']=df['Weather_Conditions']+df['Vehicle_Type']+df['Traffic_Conditions']

In [46]:
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount,imp
0,0,98,10,1.57,1,2,4,2,0,2,4.1,3.0,26.22,1321.10,81.54,5
1,1,73,50,21.32,0,2,8,1,3,2,4.5,4.2,62.61,152.21,29.02,4
2,2,79,163,6.95,2,2,9,0,3,1,3.3,3.4,48.43,1644.38,64.17,5
3,3,160,107,13.79,0,1,2,2,1,1,3.2,3.7,111.63,541.25,79.23,2
4,4,65,71,6.72,1,0,6,1,3,1,3.5,2.8,32.38,619.81,2.34,2

In [47]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Order_ID, Customer_Location, Restaurant_Location, Distance, Weather_Conditions, Traffic_Conditions, Delivery_Person_Experience, Order_Priority, Order_Time, Vehicle_Type, Restaurant_Rating, Customer_Rating, Delivery_Time, Order_Cost, Tip_Amount, imp]
Index: []

In [49]:
X=df[['Distance','Restaurant_Rating','imp']]
y=df['Delivery_Time']

In [50]:
X

     Distance  Restaurant_Rating  imp
0        1.57                4.1    5
1       21.32                4.5    4
2        6.95                3.3    5
3       13.79                3.2    2
4        6.72                3.5    2
..        ...                ...  ...
195     23.82                4.7    1
196      6.09                3.0    4
197     20.61                2.9    3
198     24.06                3.9    3
199      9.18                4.6    4

[200 rows x 3 columns]

In [51]:
y

0       26.22
1       62.61
2       48.43
3      111.63
4       32.38
        ...
195     50.39
196     90.54
197     73.20
198     53.94
199     78.58
Name: Delivery_Time, Length: 200, dtype: float64

In [52]:
X=np.array(X)
y=np.array(y)

In [53]:
X

array([[ 1.57,  4.1 ,  5.  ],
       [21.32,  4.5 ,  4.  ],
       [ 6.95,  3.3 ,  5.  ],
       [13.79,  3.2 ,  2.  ],
       [ 6.72,  3.5 ,  2.  ],
       [10.  ,  2.8 ,  1.  ],
       [ 5.15,  4.4 ,  7.  ],
       [22.57,  3.2 ,  4.  ],
       [13.19,  3.2 ,  4.  ],
       [19.56,  3.7 ,  4.  ],
       [18.34,  3.5 ,  3.  ],
       [ 3.04,  3.5 ,  5.  ],
       [ 1.34,  4.  ,  3.  ],
       [ 0.87,  2.5 ,  1.  ],
       [10.07,  4.9 ,  3.  ],
       [20.73,  3.7 ,  6.  ],
       [14.02,  4.4 ,  2.  ],
       [ 4.74,  2.5 ,  4.  ],
       [ 8.61,  2.9 ,  6.  ],
       [13.65,  2.9 ,  4.  ],
       [19.26,  4.  ,  3.  ],
       [ 5.18,  4.3 ,  6.  ],
       [ 7.14,  3.6 ,  0.  ],
       [ 5.58,  2.8 ,  3.  ],
       [11.06,  3.1 ,  6.  ],
       [ 3.61,  3.6 ,  4.  ],
       [ 2.76,  4.  ,  2.  ],
       [ 8.29,  4.7 ,  5.  ],
       [ 7.17,  4.6 ,  4.  ],
       [ 4.87,  2.8 ,  5.  ],
       [24.1 ,  2.5 ,  3.  ],
       [12.59,  4.  ,  2.  ],
       [ 8.84,  2.5 ,  1.  ],
       [ 9.51,  2.9 ,  2.  ],
       [ 8.47,  4.8 ,  5.  ],
       [23.23,  3.2 ,  3.  ],
       [16.45,  2.8 ,  2.  ],
       [16.64,  4.6 ,  4.  ],
       [ 4.79,  3.9 ,  6.  ],
       [ 2.33,  2.5 ,  5.  ],
       [ 7.87,  4.4 ,  5.  ],
       [ 8.97,  4.6 ,  0.  ],
       [ 5.27,  4.7 ,  5.  ],
       [ 2.72,  3.8 ,  7.  ],
       [ 6.54,  4.2 ,  5.  ],
       [12.44,  4.1 ,  3.  ],
       [ 3.92,  3.9 ,  3.  ],
       [ 8.23,  2.9 ,  2.  ],
       [15.87,  3.2 ,  5.  ],
       [22.31,  4.9 ,  0.  ],
       [13.09,  4.6 ,  2.  ],
       [ 1.33,  4.8 ,  2.  ],
       [16.18,  2.9 ,  1.  ],
       [12.2 ,  2.5 ,  2.  ],
       [24.68,  3.4 ,  7.  ],
       [12.27,  3.5 ,  5.  ],
       [19.52,  3.  ,  3.  ],
       [16.66,  3.3 ,  6.  ],
       [13.23,  2.6 ,  1.  ],
       [16.25,  3.1 ,  2.  ],
       [ 2.73,  4.  ,  6.  ],
       [ 1.19,  2.8 ,  4.  ],
       [ 1.44,  4.3 ,  3.  ],
       [15.93,  3.3 ,  3.  ],
       [11.44,  3.7 ,  5.  ],
       [11.18,  4.4 ,  2.  ],
       [24.9 ,  4.6 ,  6.  ],
       [12.69,  4.6 ,  4.  ],
       [ 3.12,  3.7 ,  1.  ],
       [ 8.94,  4.2 ,  4.  ],
       [22.84,  2.7 ,  3.  ],
       [14.9 ,  2.8 ,  1.  ],
       [22.1 ,  4.1 ,  2.  ],
       [18.68,  3.6 ,  3.  ],
       [ 7.6 ,  3.2 ,  3.  ],
       [ 2.29,  4.5 ,  7.  ],
       [ 6.74,  3.2 ,  3.  ],
       [16.35,  4.4 ,  3.  ],
       [12.02,  3.4 ,  5.  ],
       [24.26,  4.6 ,  2.  ],
       [ 0.56,  4.1 ,  6.  ],
       [14.09,  3.8 ,  3.  ],
       [ 9.59,  4.9 ,  1.  ],
       [21.74,  3.8 ,  5.  ],
       [ 9.17,  5.  ,  2.  ],
       [ 7.7 ,  4.7 ,  4.  ],
       [12.73,  2.5 ,  3.  ],
       [ 8.5 ,  2.6 ,  4.  ],
       [10.  ,  4.5 ,  0.  ],
       [ 2.12,  3.6 ,  3.  ],
       [ 6.09,  4.3 ,  3.  ],
       [ 3.25,  4.1 ,  4.  ],
       [ 2.23,  3.9 ,  2.  ],
       [ 8.34,  3.5 ,  7.  ],
       [13.44,  3.9 ,  4.  ],
       [22.15,  3.8 ,  6.  ],
       [12.33,  4.8 ,  4.  ],
       [20.25,  4.7 ,  5.  ],
       [18.84,  4.3 ,  3.  ],
       [10.11,  3.9 ,  3.  ],
       [ 5.09,  3.8 ,  3.  ],
       [ 9.45,  3.8 ,  3.  ],
       [13.03,  4.8 ,  3.  ],
       [11.57,  3.7 ,  2.  ],
       [12.16,  4.1 ,  6.  ],
       [ 5.08,  4.  ,  2.  ],
       [21.76,  3.2 ,  4.  ],
       [19.82,  3.8 ,  5.  ],
       [ 1.77,  3.5 ,  6.  ],
       [ 1.7 ,  4.6 ,  2.  ],
       [ 5.4 ,  4.5 ,  4.  ],
       [14.33,  2.5 ,  3.  ],
       [24.45,  4.7 ,  3.  ],
       [15.37,  3.8 ,  6.  ],
       [ 0.52,  3.7 ,  1.  ],
       [14.76,  2.7 ,  4.  ],
       [ 9.17,  3.  ,  3.  ],
       [13.48,  3.5 ,  3.  ],
       [18.18,  3.6 ,  6.  ],
       [21.16,  4.5 ,  3.  ],
       [ 8.08,  4.2 ,  2.  ],
       [21.56,  3.5 ,  6.  ],
       [ 9.62,  3.7 ,  5.  ],
       [20.49,  3.9 ,  2.  ],
       [22.32,  2.9 ,  1.  ],
       [13.61,  4.9 ,  4.  ],
       [20.77,  3.9 ,  7.  ],
       [ 7.94,  2.8 ,  7.  ],
       [18.07,  4.9 ,  7.  ],
       [ 4.61,  2.6 ,  4.  ],
       [ 1.32,  4.1 ,  5.  ],
       [18.91,  4.5 ,  4.  ],
       [ 1.32,  2.8 ,  3.  ],
       [18.  ,  5.  ,  1.  ],
       [12.9 ,  3.3 ,  5.  ],
       [22.58,  4.1 ,  1.  ],
       [15.34,  4.3 ,  2.  ],
       [ 9.64,  2.6 ,  3.  ],
       [10.42,  3.9 ,  4.  ],
       [12.63,  3.8 ,  5.  ],
       [12.7 ,  4.8 ,  6.  ],
       [12.97,  4.  ,  2.  ],
       [16.83,  3.8 ,  2.  ],
       [ 8.4 ,  4.  ,  5.  ],
       [ 5.36,  3.2 ,  5.  ],
       [14.22,  3.2 ,  5.  ],
       [ 1.09,  4.4 ,  4.  ],
       [ 1.81,  2.9 ,  1.  ],
       [ 7.09,  4.8 ,  5.  ],
       [19.46,  4.5 ,  5.  ],
       [10.65,  3.4 ,  2.  ],
       [ 9.44,  3.1 ,  7.  ],
       [ 8.7 ,  4.2 ,  5.  ],
       [10.76,  2.8 ,  4.  ],
       [16.03,  4.1 ,  1.  ],
       [14.85,  3.5 ,  4.  ],
       [ 7.87,  3.8 ,  1.  ],
       [ 9.88,  3.  ,  5.  ],
       [14.12,  4.5 ,  3.  ],
       [23.79,  3.5 ,  4.  ],
       [10.11,  3.3 ,  2.  ],
       [ 6.85,  3.8 ,  2.  ],
       [23.94,  4.8 ,  1.  ],
       [21.24,  3.6 ,  1.  ],
       [ 8.22,  2.7 ,  5.  ],
       [ 8.54,  2.5 ,  6.  ],
       [ 8.87,  3.4 ,  6.  ],
       [ 1.79,  3.4 ,  5.  ],
       [23.24,  3.8 ,  4.  ],
       [ 4.33,  3.5 ,  4.  ],
       [ 1.99,  3.1 ,  3.  ],
       [13.12,  3.6 ,  4.  ],
       [ 5.91,  3.8 ,  5.  ],
       [22.34,  2.8 ,  4.  ],
       [ 1.9 ,  2.9 ,  4.  ],
       [ 7.38,  4.3 ,  6.  ],
       [ 5.29,  3.7 ,  5.  ],
       [17.44,  4.7 ,  3.  ],
       [ 9.31,  3.3 ,  4.  ],
       [ 5.24,  2.5 ,  2.  ],
       [ 7.19,  4.3 ,  4.  ],
       [ 2.46,  3.3 ,  4.  ],
       [18.82,  4.6 ,  3.  ],
       [11.39,  3.5 ,  4.  ],
       [ 7.38,  3.3 ,  6.  ],
       [ 3.25,  4.9 ,  2.  ],
       [ 3.56,  4.  ,  3.  ],
       [ 6.6 ,  4.5 ,  7.  ],
       [23.87,  2.9 ,  2.  ],
       [10.56,  3.6 ,  3.  ],
       [15.36,  4.8 ,  2.  ],
       [ 4.33,  4.  ,  4.  ],
       [22.68,  2.9 ,  2.  ],
       [ 6.53,  3.6 ,  2.  ],
       [18.2 ,  4.8 ,  3.  ],
       [23.82,  4.7 ,  1.  ],
       [ 6.09,  3.  ,  4.  ],
       [20.61,  2.9 ,  3.  ],
       [24.06,  3.9 ,  3.  ],
       [ 9.18,  4.6 ,  4.  ]])

In [54]:
y

array([ 26.22,  62.61,  48.43, 111.63,  32.38,  60.72,  28.76,  57.28,
        47.22,  81.55,  34.68, 106.88,  23.12,  55.43,  29.29,  50.11,
        17.53,  79.64,  41.29, 105.53,  43.19,  39.7 ,  98.27,  32.22,
       105.6 ,  80.74,  22.99, 102.31,  40.22,  34.47,  87.96,  18.89,
        66.84,  67.53, 106.37,  61.59,  71.81,  66.11,  59.42,  94.66,
        39.37, 106.23,  80.66, 100.79,  78.07,  28.39,  98.89, 113.45,
        73.72,  59.07,  47.46, 105.89,  44.07,  63.55,  69.7 ,  68.07,
        15.42,  59.63,  24.49,  88.3 ,  77.06, 112.41, 115.63,  72.59,
        82.87,  85.19,  66.84,  71.98,  53.53,  72.91, 115.32,  74.07,
        65.57,  91.6 ,  69.67,  79.35,  79.09, 104.6 ,  60.18,  52.03,
        16.48,  67.22,  15.23, 113.29, 118.8 ,  20.29, 118.26, 107.95,
       109.67,  23.1 ,  41.71,  77.65,  91.85,  33.81,  21.21,  91.22,
        77.25,  67.89,  80.96, 100.6 ,  56.11,  91.33,  44.99,  22.69,
       112.83,  96.44, 119.67,  18.9 ,  76.57,  61.58, 102.06,  68.88,
        86.8 ,  57.78,  55.23,  63.79, 107.53,  92.43,  94.6 , 108.42,
        85.42,  50.16, 110.3 ,  87.07,  28.65,  40.6 ,  58.53,  34.51,
        16.98, 113.28,  72.64,  32.44, 114.  ,  36.63,  73.82,  79.73,
        23.54, 109.15, 115.69,  29.12,  70.4 , 116.43,  62.32,  97.6 ,
        80.62,  99.93,  96.51,  18.67,  46.33, 103.89,  88.24,  49.57,
        99.99,  78.64,  98.69,  32.57,  21.7 ,  22.48,  95.64,  26.47,
        60.19, 109.1 ,  32.93,  39.18, 103.35,  78.69,  22.35,  67.91,
        40.05,  69.78, 114.28,  74.41,  64.18,  82.96,  93.2 ,  50.02,
        48.26, 111.18,  80.11,  97.07,  84.34, 114.21,  56.78, 100.28,
        30.49,  89.21,  37.65, 106.64,  74.95, 105.41,  82.62, 101.25,
        98.75,  90.18, 119.46,  50.39,  90.54,  73.2 ,  53.94,  78.58])

In [55]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [56]:
X_train

array([[24.26,  4.6 ,  2.  ],
       [20.61,  2.9 ,  3.  ],
       [ 4.79,  3.9 ,  6.  ],
       [11.06,  3.1 ,  6.  ],
       [ 9.62,  3.7 ,  5.  ],
       [23.82,  4.7 ,  1.  ],
       [ 4.87,  2.8 ,  5.  ],
       [13.65,  2.9 ,  4.  ],
       [ 8.4 ,  4.  ,  5.  ],
       [12.73,  2.5 ,  3.  ],
       [ 0.52,  3.7 ,  1.  ],
       [22.34,  2.8 ,  4.  ],
       [10.  ,  2.8 ,  1.  ],
       [20.77,  3.9 ,  7.  ],
       [13.48,  3.5 ,  3.  ],
       [18.68,  3.6 ,  3.  ],
       [12.7 ,  4.8 ,  6.  ],
       [18.84,  4.3 ,  3.  ],
       [ 5.91,  3.8 ,  5.  ],
       [12.33,  4.8 ,  4.  ],
       [ 4.33,  3.5 ,  4.  ],
       [20.25,  4.7 ,  5.  ],
       [12.59,  4.  ,  2.  ],
       [ 1.34,  4.  ,  3.  ],
       [23.23,  3.2 ,  3.  ],
       [21.16,  4.5 ,  3.  ],
       [ 5.27,  4.7 ,  5.  ],
       [10.56,  3.6 ,  3.  ],
       [ 6.09,  4.3 ,  3.  ],
       [15.34,  4.3 ,  2.  ],
       [ 1.33,  4.8 ,  2.  ],
       [ 7.94,  2.8 ,  7.  ],
       [23.94,  4.8 ,  1.  ],
       [ 8.97,  4.6 ,  0.  ],
       [18.18,  3.6 ,  6.  ],
       [15.37,  3.8 ,  6.  ],
       [ 2.76,  4.  ,  2.  ],
       [12.63,  3.8 ,  5.  ],
       [ 5.09,  3.8 ,  3.  ],
       [14.33,  2.5 ,  3.  ],
       [ 6.95,  3.3 ,  5.  ],
       [16.35,  4.4 ,  3.  ],
       [ 3.92,  3.9 ,  3.  ],
       [ 6.6 ,  4.5 ,  7.  ],
       [ 4.33,  4.  ,  4.  ],
       [ 7.7 ,  4.7 ,  4.  ],
       [ 6.85,  3.8 ,  2.  ],
       [16.45,  2.8 ,  2.  ],
       [15.36,  4.8 ,  2.  ],
       [ 1.19,  2.8 ,  4.  ],
       [ 7.14,  3.6 ,  0.  ],
       [12.97,  4.  ,  2.  ],
       [ 9.45,  3.8 ,  3.  ],
       [ 9.51,  2.9 ,  2.  ],
       [ 3.04,  3.5 ,  5.  ],
       [18.2 ,  4.8 ,  3.  ],
       [23.79,  3.5 ,  4.  ],
       [ 5.15,  4.4 ,  7.  ],
       [ 8.29,  4.7 ,  5.  ],
       [ 8.08,  4.2 ,  2.  ],
       [ 6.72,  3.5 ,  2.  ],
       [ 8.84,  2.5 ,  1.  ],
       [16.83,  3.8 ,  2.  ],
       [14.22,  3.2 ,  5.  ],
       [ 1.7 ,  4.6 ,  2.  ],
       [ 5.36,  3.2 ,  5.  ],
       [18.34,  3.5 ,  3.  ],
       [ 1.44,  4.3 ,  3.  ],
       [24.45,  4.7 ,  3.  ],
       [ 1.09,  4.4 ,  4.  ],
       [ 8.87,  3.4 ,  6.  ],
       [ 1.57,  4.1 ,  5.  ],
       [24.06,  3.9 ,  3.  ],
       [10.76,  2.8 ,  4.  ],
       [22.84,  2.7 ,  3.  ],
       [20.49,  3.9 ,  2.  ],
       [11.44,  3.7 ,  5.  ],
       [ 6.54,  4.2 ,  5.  ],
       [21.24,  3.6 ,  1.  ],
       [ 7.17,  4.6 ,  4.  ],
       [ 7.87,  4.4 ,  5.  ],
       [ 1.77,  3.5 ,  6.  ],
       [14.85,  3.5 ,  4.  ],
       [ 7.87,  3.8 ,  1.  ],
       [ 3.61,  3.6 ,  4.  ],
       [ 5.58,  2.8 ,  3.  ],
       [ 7.38,  3.3 ,  6.  ],
       [ 1.81,  2.9 ,  1.  ],
       [14.09,  3.8 ,  3.  ],
       [ 2.33,  2.5 ,  5.  ],
       [23.24,  3.8 ,  4.  ],
       [ 8.23,  2.9 ,  2.  ],
       [13.44,  3.9 ,  4.  ],
       [16.03,  4.1 ,  1.  ],
       [ 2.72,  3.8 ,  7.  ],
       [10.42,  3.9 ,  4.  ],
       [13.79,  3.2 ,  2.  ],
       [ 5.08,  4.  ,  2.  ],
       [12.2 ,  2.5 ,  2.  ],
       [18.  ,  5.  ,  1.  ],
       [ 7.19,  4.3 ,  4.  ],
       [ 9.31,  3.3 ,  4.  ],
       [ 3.25,  4.9 ,  2.  ],
       [22.31,  4.9 ,  0.  ],
       [ 0.56,  4.1 ,  6.  ],
       [ 8.47,  4.8 ,  5.  ],
       [22.57,  3.2 ,  4.  ],
       [ 5.4 ,  4.5 ,  4.  ],
       [ 3.25,  4.1 ,  4.  ],
       [21.74,  3.8 ,  5.  ],
       [ 5.29,  3.7 ,  5.  ],
       [ 2.46,  3.3 ,  4.  ],
       [ 2.12,  3.6 ,  3.  ],
       [13.19,  3.2 ,  4.  ],
       [ 0.87,  2.5 ,  1.  ],
       [16.25,  3.1 ,  2.  ],
       [13.12,  3.6 ,  4.  ],
       [18.91,  4.5 ,  4.  ],
       [ 4.74,  2.5 ,  4.  ],
       [22.1 ,  4.1 ,  2.  ],
       [ 7.38,  4.3 ,  6.  ],
       [12.9 ,  3.3 ,  5.  ],
       [ 1.79,  3.4 ,  5.  ],
       [11.39,  3.5 ,  4.  ],
       [15.93,  3.3 ,  3.  ],
       [24.68,  3.4 ,  7.  ],
       [19.82,  3.8 ,  5.  ],
       [13.09,  4.6 ,  2.  ],
       [ 6.09,  3.  ,  4.  ],
       [13.23,  2.6 ,  1.  ],
       [15.87,  3.2 ,  5.  ],
       [10.  ,  4.5 ,  0.  ],
       [ 5.18,  4.3 ,  6.  ],
       [16.66,  3.3 ,  6.  ],
       [10.11,  3.3 ,  2.  ],
       [22.68,  2.9 ,  2.  ],
       [ 4.61,  2.6 ,  4.  ],
       [16.64,  4.6 ,  4.  ],
       [ 9.88,  3.  ,  5.  ],
       [ 6.53,  3.6 ,  2.  ],
       [21.32,  4.5 ,  4.  ],
       [16.18,  2.9 ,  1.  ],
       [19.46,  4.5 ,  5.  ],
       [ 1.32,  4.1 ,  5.  ],
       [ 9.44,  3.1 ,  7.  ],
       [11.57,  3.7 ,  2.  ],
       [10.11,  3.9 ,  3.  ],
       [ 9.17,  3.  ,  3.  ],
       [ 8.5 ,  2.6 ,  4.  ],
       [ 7.6 ,  3.2 ,  3.  ],
       [21.56,  3.5 ,  6.  ],
       [ 9.18,  4.6 ,  4.  ],
       [19.26,  4.  ,  3.  ],
       [23.87,  2.9 ,  2.  ],
       [14.9 ,  2.8 ,  1.  ],
       [21.76,  3.2 ,  4.  ],
       [10.07,  4.9 ,  3.  ],
       [ 2.23,  3.9 ,  2.  ],
       [ 5.24,  2.5 ,  2.  ],
       [13.03,  4.8 ,  3.  ]])

In [57]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [60]:
value=np.array([[15.73,  4.5 ,  4.]])

model.predict(value)
y_pred=model.predict(X_test)

In [61]:
mse=mean_squared_error(y_test,y_pred)

In [62]:
mse

894.029170265745

In [66]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score


mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
mae=mean_absolute_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [67]:
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("Mean Absolute Error (MAE):", mae)
print("R² Score:", r2)

Mean Squared Error (MSE): 894.029170265745
Root Mean Squared Error (RMSE): 29.900320571287278
Mean Absolute Error (MAE): 25.14105799489683
R² Score: 0.03336829116423823

In [70]:
df2=pd.read_csv("Food_Delivery_Time_Prediction.csv")